### ISSUE TITLE
Encrypt password before sending to databse

### ISSUE THREAD

**Issue by Annageorg** [JoelPWK/cohort-jan-21#54]

**Comment by dillonago** [comment]
Hi, I completed this. Am I allowed to push my code to a branch and start a pull request that can get merged?

**Comment by Annageorg** [comment]
> Hi, I completed this. Am I allowed to push my code to a branch and start a pull request that can get merged?

Hi @dillonago! Not sure how you found our repo, or why you would like to contribute to our project, but thank you for leaving a comment and offering help. This project is part of an assessment and used to showcase our own skills, so thank you again for the offer, but we have to kindly refuse.
